version: "3"

services: 
  db:
    image: postgres
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: budgetApp
    volumes: 
      - "./db/data:/var/lib/postgresql/data"
      - "./db/init:/docker-entrypoint-initdb.d"
